on: [issues]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Tag issues
    steps:
    - name: Issue tagging
      id: hello
      uses: christopheranderson/github-action-playground@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"